Scalingo/cli

apps/run.go
Check if the env variable has really been splitted into 2 strings
=> Env variable now correctly parsed Fixes #119

cmd/autocomplete/collaborators_add.go
When you are completing by doing `<tab><tab>`, `collaborators-add` can have a lot of requests to do depending on you apps' number.
=> Fix #137 : collaborators-add completion now uses goroutines

cmd/destroy.go
Two ways to destroy an app:
```
scalingo destroy my-app
scalingo -a my-app destroy
```
=> Make destroy command more flexible

apps/destroy.go
`scalingo destroy` was always run, whatever appname you gave.
I thought it would be better to check if the app is existing or not first.
So two requests instead of one, but the user has to type its app name again to confirm.
If he has to confirm an app that doesn't exists, it's even more bad than a 100ms request.
=> Fix #151: Destroy command is always run

cmd/suggestions.go, scalingo/main.go
https://github.com/Scalingo/cli/issues/157
Suggest commands if the user has done a typo, it works by showing commands that match the two first/last characters of his command, i.e:
```
scalingo cops
No help topic for 'cops'
You might be looking for:
- 'apps'
- 'ps'
- 'collaborators'
- 'collaborators-add'
- 'collaborators-remove'
```
The following commands match `co.*` or `.*ps`:
* ap**ps**
* **ps**
* **co**llaborators
* **co**llaborators-add
* **co**llaborators-remove
=> Command suggestions

cmd/suggestions.go, config/auth.go
- Fixed suggestions showing the whole list of commands when passing no arguments
- Previous method `bufio.NewReader().ReadString("\n")` wasn't compatible with dpl
=> Fix #166 and revert to Scanln(&login) for dpl comp

Godeps/Godeps.json, README.md, cmd/commands.go, cmd/deployments.go, deployments/deploy.go, deployments/follow.go, deployments/logs.go, deployments/push.go, vendor/github.com/Scalingo/go-scalingo/deployments.go
Waiting for Scalingo/go-scalingo#13 to be merged before merging this one.
```
╰─$ scalingo -a clitest deploy https://github.com/Scalingo/sample-ruby-sinatra/archive/master.tar.gz
-----> Downloading the source code
[NEW] New deploy: bfd30404-6855-4980-b4f8-2986b97d7881 from etiennem
[LOG] -----> Buildpack version 1.3.0
[LOG] -----> Compiling Ruby/Rack
[LOG] -----> Using Ruby version: ruby-2.3.3
[LOG] -----> Installing dependencies using 1.9.7
[LOG] Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
[LOG] Fetching gem metadata from https://rubygems.org/..........
[LOG] Fetching version metadata from https://rubygems.org/..
[LOG] Using bundler 1.9.7
[LOG] Installing tilt 1.4.1
[LOG] Installing rack 1.5.2
[LOG] Installing …
```
=> Add `scalingo deploy` to deploy an archive

Godeps/Godeps.json, cmd/deployments.go, deployments/deploy.go, deployments/deploy_war.go, vendor/github.com/Scalingo/go-scalingo/apps.go, vendor/github.com/Scalingo/go-scalingo/client.go, vendor/github.com/Scalingo/go-scalingo/deployments.go, vendor/github.com/Scalingo/go-scalingo/sources.go
Fix #278 
Not yet ready to be merged.
I have an error when reaching the API deployment endpoint. We make a HEAD request to the given URL in order to get the `Content-Type` and the `Content-Length` header (https://github.com/Scalingo/api/blob/master/app/controllers/app/deployments_controller.rb#L263).
But S3 returns a 403 response. I tried adding the `s3:HeadObject` right to the dev user but it does not change anything. Any idea on how to solve this one?
By the way, the error is not very nice for the end user as it is a 500 error on the API side so the CLI displays:
```
!     An error occured:
server internal error - our team has been notified
```
I am wondering how to bubble up nicely the error to the CLI.
=> Add deploy war option

config/auth.go
and recreate a new one instead of crashing
=> Adds message if auth file is corrupted

scalingo/main.go
=> Correctly autocomplete -a --app -r --remote flags when they are the first args of a command

CHANGELOG, cmd/help.go, scalingo/main.go
=> Correctly display help whe nthe users types an unknown command

README.md, config/config.go, update/check.go
=> Add a way to disable update checker making an http request

CHANGELOG, cmd/commands.go, cmd/self.go
```
$ scalingo self
-----> You are logged in as admin (admin@scalingo.com)
$ scalingo whoami
-----> You are logged in as admin (admin@scalingo.com)
$ scalingo self                                                                         
-----> Currently unauthenticated
Trying login with SSH…                                                                                                                                                                
!     SSH connection failed.                                                                                                                                                                
Trying login with user/password:
```
Fix #350
=> Add self command (and whoami alias)

CHANGELOG.md, Gopkg.lock, Gopkg.toml, alerts/list.go, cmd/alerts.go, vendor/github.com/Scalingo/go-scalingo/addons.go, vendor/github.com/Scalingo/go-scalingo/alerts.go, vendor/github.com/Scalingo/go-scalingo/client.go, vendor/github.com/Scalingo/go-scalingo/http/client.go
Related to Scalingo/scalingo-alerter-service#93
=> Add duration-before-trigger flag to alert creation and update

CHANGELOG.md, Gopkg.lock, domains/list.go, vendor/github.com/Scalingo/go-scalingo/client.go, vendor/github.com/Scalingo/go-scalingo/domains.go
Fix #409
```
$ go build -o cli ./scalingo && ./cli -a my-app domains
+----------------+--------------------------------+
|     DOMAIN     |            TLS/SSL             |
+----------------+--------------------------------+
| example.com    | (LE In use) Valid until        |
|                | 2019-07-01 10:57:26 +0200 CEST |
| *.example.net  | (LE Error) Valid until         |
|                | 2019-04-12 19:40:07 +0200 CEST |
| *.example.eu   | (LE In use) Valid until        |
|                | 2019-06-12 09:00:11 +0200 CEST |
| example.net    |                              - |
| example.eu     |                              - |
+----------------+--------------------------------+
```
=> Display Let's Encrypt certificate status

CHANGELOG.md, Gopkg.lock, apps/info.go, cmd/apps.go, cmd/commands.go, cmd/domains.go, cmd/rename.go, vendor/github.com/Scalingo/go-scalingo/apps.go
```
scalingo --app scalingo-api-production apps-info
+----------------+----------+
|    SETTINGS    |  VALUE   |
+----------------+----------+
| Force HTTPS    | false    |
| Sticky Session | false    |
| Stack          | scalingo |
| Status         | running  |
+----------------+----------+
```
Fix #437
=> Add the apps-info command

CHANGELOG.md, appdetect/git.go, appdetect/git_test.go
=> Fix Git remote URL parsing to detect app name

CHANGELOG.md, Gopkg.lock, cmd/commands.go, cmd/databases.go, db/backups_config.go, db/databases.go, vendor/github.com/Scalingo/go-scalingo/databases.go
```
$ scalingo --app my-app --addon ad-d4903c5a-7b38-4fca-950a-54a34ae84ca4 backups-config --disable-scheduling
-----> Periodic backups are disabled
$ scalingo --app my-app --addon ad-d4903c5a-7b38-4fca-950a-54a34ae84ca4 backups-config --schedule-at 3
-----> Periodic backups will be done daily at 3:00 CEST
```
Fix #454
=> Add periodic backups configuration commands

cmd/backups.go
```
╰─$ scalingo --app MY-APP backup-download --addon ad-78fbfa75-367d-53da-98a9-9d40d3ea0dac --backup 5d3e37018664ac757c331465
/!\  DEPRECATED: please use backups-download instead of this command
305 B / 305 B [==================================================================================================================================================================] 100.00% 0s
===> 20190729020001_my-app-3536.tar.gz
```
Fix #459
=> backup-download missing flags

CHANGELOG.md, Gopkg.lock, vendor/github.com/Scalingo/go-scalingo/events_boilerplate.go, vendor/github.com/Scalingo/go-scalingo/events_structs.go, vendor/github.com/Scalingo/go-scalingo/events_user.go, vendor/github.com/Scalingo/go-scalingo/scm_integrations.go
```
╰─$ go build -o ./scalingo/scalingo ./scalingo && SCALINGO_REGION=local SCALINGO_AUTH_URL=http://172.17.0.1:1234 SCALINGO_API_URL=http://172.17.0.1:3001 SSH_HOST=localhost:2200 ./scalingo/scalingo user-timeline
* Mon Jul 29 2019 09:38:43 - New User - You joined Scalingo. Hooray! <admin-auth (admin-auth@scalingo.com)>
```
Fix #471
=> Add support for new_user event

.ackrc, CHANGELOG.md, scmintegrations/create.go, scmintegrations/delete.go, scmintegrations/import_keys.go, scmintegrations/list.go
```
╰─$ go build -o ./scalingo/scalingo ./scalingo && SCALINGO_REGION=local SCALINGO_AUTH_URL=http://172.17.0.1:1234 SCALINGO_API_URL=http://172.17.0.1:3001 SSH_HOST=localhost:2200 ./scalingo/scalingo user-timeline
* Wed Aug 28 2019 15:19:41 - New Integration    - GitHub account 'EtienneM' has been authorized <admin-auth (admin-auth@scalingo.com)>
* Wed Aug 28 2019 15:19:41 - New Integration    - GitHub Enterprise (https://ghe.scalingo.com) account 'EtienneM' has been authorized <admin-auth (admin-auth@scalingo.com)>
* Wed Aug 28 2019 14:38:56 - Delete Integration - GitHub account 'EtienneM' has been revoked <admin-auth (admin-auth@scalingo.com)>
```
To be merged after ~https://github.com/Scalingo/go-scalingo/pull/135 and #458~
This PR was just an update of go-scalingo but I ended up …
=> Display new SCM events

CHANGELOG.md, db/redis_console.go
```
╰─$ scalingo --app test-etienne redis-console      
!     An error occured:
Redis console is not available when TLS connections are enforced
```
Fix #479
=> Redis console better error message if Force TLS

cmd/integration_link.go
```
╰─$ scalingo --app test-etienne integration-link-create https://framagit.org/Titizebioutifoul/sample-go-martini
? Branch to auto-deploy (empty to disable):
? Automatically deploy review apps: Yes
? Automatically destroy review apps when the pull/merge request is closed: Yes
? Hours before automatically destroying the review apps: 0
? Automatically destroy review apps after some time without deploy/commits: No
-----> Your app 'test-etienne' is linked to the repository https://framagit.org/Titizebioutifoul/sample-go-martini.
╭─emichon@biniou ~/Documents/Scalingo/golang/src/github.com/Scalingo/cli 2.4.2‹fix/484/default_destroy_stale*›
╰─$ scalingo --app test-etienne integration-link
Application: test-etienne (5d6d0d2bb4553d00019d22b6)
Integration: GitLab self-hosted …
```
=> Default destroy on stale is No

CHANGELOG.md, Gopkg.lock, Gopkg.toml, cmd/integration_link.go, config/config.go, integrationlink/create.go, integrationlink/params.go, integrationlink/show.go, integrationlink/update.go, vendor/github.com/Scalingo/go-scalingo/client.go, vendor/github.com/Scalingo/go-scalingo/http/api_request.go, vendor/github.com/Scalingo/go-scalingo/http/client.go, vendor/github.com/Scalingo/go-scalingo/http/errors.go, vendor/github.com/Scalingo/go-scalingo/scm_repo_link.go, vendor/github.com/Scalingo/go-scalingo/version.go
```
╰─$ go build -o ./scalingo/scalingo ./scalingo && DEBUG=1 ./scalingo/scalingo --region osc-fr1 --app my-app integration-link
[DEBUG]2019/09/24 14:17:16 [Regions] Use the cache
[DEBUG]2019/09/24 14:17:16 [AppDetect] App name is my-app
[DEBUG]2019/09/24 14:17:16 [Regions] Use the cache
[DEBUG]2019/09/24 14:17:16 [API] POST https://auth.scalingo.com/v1/tokens/exchange
[DEBUG]2019/09/24 14:17:16       User Agent: 
[DEBUG]2019/09/24 14:17:16       Headers: map[User-Agent:[]]
[DEBUG]2019/09/24 14:17:16       Params: map[]
[DEBUG]2019/09/24 14:17:16       Request ID: 619d9539-f619-48a1-a668-b7da855f9b70
[DEBUG]2019/09/24 14:17:16       Duration: 243.335141ms
[DEBUG]2019/09/24 14:17:16 [API] GET https://api.osc-fr1.scalingo.com/v1/apps/my-app/scm_repo_link?
[DEBUG]2019/09/24 14:17:16 …
```
=> Do not get the SCM integration when showing the integration link

Gopkg.lock, apps/create.go, utils/errors.go, vendor/github.com/Scalingo/go-scalingo/http/errors.go
```
$ SCALINGO_REGION=agora-fr1 scalingo create totoapp
Application creation has been disabled on the currently used region: agora-fr1
Either configure your CLI to use another default region, then create your application:
scalingo config --region osc-fr1
scalingo create totoapp
Or use the region flag to specify the region explicitely for this command:
scalingo --region osc-fr1 create totoapp
List of available regions:
- osc-fr1 (Paris - Outscale)
```
=> Display a nice message when creating an app in a disabled region

Gopkg.lock, Gopkg.toml, cmd/region_migrations.go, region_migrations/confirmations.go, region_migrations/refresher.go, region_migrations/run.go, vendor/github.com/Scalingo/go-scalingo/region_migrations.go
Waiting for final release of go-scalingo
=> Add ability to pass --new-name to migration-create for same-region migration

CHANGELOG.md, cmd/db_tunnel.go, db/tunnel.go
Fix #516
* Do not reuse ssh.Signer, the connection to ssh agent might be broken
* Do not retry the connection if the server closed the connection
* Add --bind to db-tunnel to bind a custom command. This is helpful for docker setups where listening on localhost wont make it available on the docker0 interface
=> Fix: do not fail on short connections

CHANGELOG.md, cmd/error.go
```
╰─$ go build -o scalingo-cli ./scalingo && ./scalingo-cli --app unknown-app run bash
!     The application was not found on the region agora-fr1. You can try on a different region with 'scalingo --region osc-fr1 ...'.
```
Related to https://github.com/Scalingo/one-stop-shop/issues/34
=> Error message if unknown app suggest to try on a different region

CHANGELOG.md, cmd/error.go
```
╰─$ go build -o scalingo-cli ./scalingo && ./scalingo-cli --app unknown-app run bash
!     The application was not found on the region agora-fr1.
!     You can try on a different region with 'scalingo --region osc-fr1 ...'.
!     
!     List of available regions from your account is accessible with 'scalingo regions'.
```
Related to https://github.com/Scalingo/one-stop-shop/issues/34
=> Improve error message when querying unknown app

apps/create.go, cmd/create.go, cmd/error.go
Close #526 
Examples:
```bash
➜ ./main create te        
!     An error occured:
* name → should contain between 6 and 32 characters
```
```bash
➜ ./main -a test-cli integration-link-create https://github.com/scalingo/test
? Branch to auto-deploy (empty to disable): 
? Automatically deploy review apps: No
!     An error occured:
fail to create the repo link: fail to create the SCM repo link: server internal error - our team has been notified
```
=> Fix displaying of errors

region_migrations/refresher.go
=> [Migration] Retry if refresh errored

CHANGELOG.md, Gopkg.lock, Gopkg.toml, vendor/github.com/Scalingo/go-scalingo/events_boilerplate.go
Fixed in the latest version of go-scalingo (https://github.com/Scalingo/go-scalingo/pull/161 and https://github.com/Scalingo/go-scalingo/pull/162)
```
╰─$ go build -o scalingo-cli ./scalingo && ./scalingo-cli --app biniou timeline
[...]
* Tue Mar 24 2020 11:17:53 - Addon Updated  - Addon PostgreSQL biniou_9013 updated, status provisioning -> running <scalingo-platform (deploy@scalingo.com)>
* Tue Mar 24 2020 11:17:53 - Restart        - containers have been restarted <Addon PostgreSQL>
* Tue Mar 24 2020 11:17:53 - Edit Variable  - 'SCALINGO_POSTGRESQL_URL' modified <Addon PostgreSQL>
[...]
```
Fix #556
Fix #530
=> Fix addon_updated, start_region_migration, restart and edit_variable event types

.gitignore, CHANGELOG.md, Gopkg.lock, Gopkg.toml, cmd/commands.go, cmd/log_drains.go, log_drains/list.go, vendor/github.com/Scalingo/go-scalingo/client.go, vendor/github.com/Scalingo/go-scalingo/events_structs.go, vendor/github.com/Scalingo/go-scalingo/log_drains.go, vendor/github.com/Scalingo/go-scalingo/version.go
- Add list command
- Add a vsocde config file to debug CLI
Example
```bash
$ scalingo log-drains --app my-app
+------------------------------------+
|                 URL                |
+------------------------------------+
| ovh://:id@region.logs.ovh.com:6514 |
| tcp+tls://localhost:10303          |
+------------------------------------+
```
Fix #553
=> Log drains list command

CHANGELOG.md, Gopkg.lock, Gopkg.toml, README.md, cmd/commands.go, cmd/log_drains.go, log_drains/add.go, vendor/github.com/Scalingo/go-scalingo/log_drains.go, vendor/github.com/Scalingo/go-scalingo/version.go
- Add `log-drains-add` command
Example
```bash
$ scalingo log-drains-add --app sample-go-martini --type papertrail --host logs.papertrailapp.com --port 12345
-----> Log Drain tcp+tls://logs.papertrailapp.com:12345 has been add to the application
```
Fix #552
=> Log drains add command

CHANGELOG.md, Gopkg.lock, Gopkg.toml, cmd/autocomplete/domains_remove.go, cmd/autocomplete/log_drains_remove.go, cmd/commands.go, cmd/log_drains.go, log_drains/remove.go, vendor/github.com/Scalingo/go-scalingo/log_drains.go, vendor/github.com/Scalingo/go-scalingo/version.go
Add remove command
Example:
```bash
$ scalingo log-drains-remove --app sample-go-martini tcp+tls://logs.papertrailapp.com:12345
-----> The log drain: tcp+tls://logs.papertrailapp.com:12345 has been deleted
```
Fix #554
=> Log drains: delete command

CHANGELOG.md, Gopkg.lock, README.md, vendor/github.com/Scalingo/go-scalingo/events_structs.go, vendor/github.com/Scalingo/go-scalingo/log_drains.go, vendor/github.com/Scalingo/go-scalingo/version.go
We need this PR (https://github.com/Scalingo/go-scalingo/pull/169) for the log
drain...
This PR also fixes #569
=> Update go-scalingo from 4.5.3 to 4.5.5

CHANGELOG.md, Gopkg.lock, Gopkg.toml, cmd/log_drains.go, log_drains/add.go, vendor/github.com/Scalingo/go-scalingo/log_drains.go, vendor/github.com/Scalingo/go-scalingo/version.go
User will provide `addon <addon_uuid>` to the `log-drains` command.
Example:
```bash
$ scalingo --app my-app --addon ad-1234567-1123 log-drains-add \
--type papertrail --host logs.papertrailapp.com --port 10303
```
Or add a log drains to all addons linked to the app:
```bash
$ scalingo --app my-app --with-addon log-drains-add \
--type papertrail --host logs.papertrailapp.com --port 10303
```
Fix #571
=> add log drain to an addon

CHANGELOG.md, Gopkg.lock, Gopkg.toml, cmd/log_drains.go, log_drains/remove.go, vendor/github.com/Scalingo/go-scalingo/log_drains.go, vendor/github.com/Scalingo/go-scalingo/version.go
Command: remove a log drain from a DB (with addon uuid)
Example:
With an application `app-1` with 2 addons `` and ``
```bash
$ scalingo --app app-1 log-drains-remove tcp+tls://logs.papertrailapp.com:10303
-----> Log drain tcp+tls://logs.papertrailapp.com:10303 has been deleted from the application app-1
-----> Log drain tcp+tls://logs.papertrailapp.com:10303 has been deleted from the addon Scalingo Redis
-----> Log drain tcp+tls://logs.papertrailapp.com:10303 has been deleted from the addon Scalingo Mongo
$ scalingo --app app-1 --addon ad-1234567-1123 log-drains-remove tcp+tls://logs.papertrailapp.com:10303
-----> Log drain tcp+tls://logs.papertrailapp.com:10303 has been deleted from the addon Scalingo Redis
$ scalingo --app app-1 --only-app log-drains-remove …
```
=> Remove log drains from db

cmd/log_drains.go, log_drains/list.go
```bash
$ scalingo --app my-app log-drains --with-addons
-----> fail to list the log drains of the addon ad-3333333-a2a5-4136-95f2-3cd90803a333: 400 Bad Request → This addon doesn't support log drains
+-------------+----------------------------------------+
|     NAME    |                   URL                  |
+-------------+----------------------------------------+
| my-app      | tcp+tls://logs.papertrailapp.com:10303 |
| Redis       | ovh://:id@gra3.logs.ovh.com:6514       |
+-------------+----------------------------------------+
```
Fix #583
=> Continue to list log drains of application even if an addon is not a database

.github/pull_request_template.md
I think we often forget to add the chngelog entry. I hope that this change will make it less forgettable.
=> [dev] Add a PR template

CHANGELOG.md, apps/scale.go
Now errors are printed like:
```bash
scalingo --app sample-go-martini scale M:0 Test:0
!     An error occurred:
* M → containers type not found
* Test → containers type not found
Your available container types are: 'web', 'other'.
Example of usage:
scalingo --app my-app scale web:2 worker:1
scalingo --app my-app scale web:1:XL
scalingo --app my-app scale web:+1 worker:-1
Use 'scalingo scale --help' for more information
```
Related to https://github.com/Scalingo/api/pull/1799
Related to https://github.com/Scalingo/one-stop-shop/issues/191
Related to [OPSB-49]
[OPSB-49]: https://scalingo.atlassian.net/browse/OPSB-49
=> Add informative error

cmd/integration_link.go, integrationlink/create.go
I didn't add a CHANGELOG entry, it does not seem worth it...
```
go build -o scalingo-cli ./scalingo && ./scalingo-cli -a biniou integration-link-create https://github.com/EtienneM/sample-go-martinii
!     Fail to create SCM repository integration: the repository has not been found
!     Check https://github.com/EtienneM/sample-go-martinii exists and you have the correct permissions
!     https://doc.scalingo.com/platform/deployment/deploy-with-github
```
Fix #522
=> fix(integration-link-create): clearer error message in case of unknown repository

CHANGELOG.md, cmd/commands.go, cmd/env.go, env/display.go
```
╰─$ go build -o scalingo-cli ./scalingo && ./scalingo-cli -a biniou env-get DATABASE_URL
postgres://biniou_123:ZkH-Ri123WIs123haBQ3@biniou-123.postgresql.dbs.scalingo.com:35123/biniou_123?sslmode=prefer
```
Fix #439
=> feat(env-get): add command

CHANGELOG.md, db/backup_download.go
```
╰─$ go build -o scalingo-cli ./scalingo && ./scalingo-cli -a my-app backups-download --addon ad-c98ed74e-fbe6-4154-9806-e957cb9304e7 --output - > b
-----> Selected the most recent backup
305 B / 305 B [======================================//===========================================] 100.00% 0s
╭─etiennem@biniou ~/Documents/Scalingo/golang/src/github.com/Scalingo/cli ‹2.7.2› ‹fix/645/backup_dl_output*› 
╰─$ head b                                                                                                                                         
?N0p/G#Kγn
$.p/ -Pa.ˁĀA,b֕+x
l~ .(xI+;EaB5q,+?0l>qW>
kinr{6pnN&WEdMƢC(h"CgHYZ!EYgwU  zEfj|w0ZVx
```
Fix #645
=> fix(backup_download): no log on stdout when using '--output -' flag

CHANGELOG.md, cmd/deployments.go, db/backup_download.go, deployments/logs.go
```
╰─$ go build -o scalingo-cli ./scalingo && ./scalingo-cli -a my-app deployment-logs                                     
-----> Selected the most recent deployment (ca874847-654d-455e-a7d5-dcab193413f1)                                                                                                                           
<-- Start deployment of my-app -->                                                                                                                                                                                
Fetching source code                                                                                                                                                                                        
...
```
Fix …
=> feat(deployment-logs): display the last deployment logs if none is provided

CHANGELOG.md, cmd/integration_link.go
```
$ scalingo -a dadazdazdazdaz integration-link-create https://gitlab.com/Moi/repo --auto-deploy --branch master
!     Fail to create SCM repository integration: the SCM API returned a 401 error.
!     Did you revoked the Scalingo token from your profile? In such situation, you may want to remove and re-create the SCM integration.
!     
!     The complete error message from the SCM API is: Request forbidden (403): {error: invalid_token}, {error_description: Token was revoked. You have to re-authorize from the user.}
```
=> feat(integration-link-create): better catch 401 from SCM API

CHANGELOG.md, db/backup_download.go
Add loops to range over the last backups until we find a successful one to download.
Still return an error if there is none.
Fix #657
=> fix(backup-download) Now download the last successful backup

CHANGELOG.md, apps/run.go, apps/run_test.go
Fixes #673.
I took the liberty of adding a couple of tests for the `buildEnv` function. I don't write Go daily, so it's likely I did something suboptimally, please feel free to let me know.
=> fix(run): allow an equals sign (=) in env var values

cmd/error.go, crontasks/list.go, deployments/list.go
Displaying an empty table when there is nothing is the current behaviour. See for instance the collaborators, autoscalers, alerts, etc. 
Related to [CRON-66]
[CRON-66]: https://scalingo.atlassian.net/browse/CRON-66
=> fix(crontasks): display an empty table in case of 404

CHANGELOG.md, cmd/deployments.go, deployments/deploy.go, deployments/deploy_war.go
=> Implemented deploy --no-follow flag

CHANGELOG.md, README.md, apps/routing_settings.go, cmd/commands.go, cmd/routing_settings.go, vendor/github.com/Scalingo/go-scalingo/v4/apps.go
=> feat(router-logs): add command to enable/disable router-logs

CHANGELOG.md, update/check.go
=> fix(update): change warning message stream from stdout to stderr

cmd/addons.go, cmd/autocomplete/addons_remove.go
Fix #699
```
╰─$ go build -o scalingo-cli ./scalingo && ./scalingo-cli -a biniou addons-info ad-97fe3f10-ed53-4459-8e40-bb41985562d1
+------------------------+------------------------+
| Database Type          | postgresql             |
| Version                | 13.3.0-2               |
| Status                 | running                |
| Plan                   | postgresql-starter-512 |
| Force TLS              | disabled               |
| Internet Accessibility | disabled               |
+------------------------+------------------------+
```
=> fix(addons-info): remove the need for the --addon option

term/password.go
The syscall package documentation states:
> Package syscall contains an interface to the low-level operating system primitives. The details vary depending on the underlying system. [...] The primary use of syscall is inside other packages that provide a more portable interface to the system, such as "os", "time" and "net". Use those packages rather than this one if you can.
https://pkg.go.dev/syscall
With this PR, the CLI compiles again on all OS
=> fix(term): prefer the use of the os package rather than syscall

addons/list.go, apps/create.go, apps/run/run_unix.go, cmd/autocomplete/addons_add.go, cmd/autocomplete/addons_upgrade.go, cmd/autocomplete/collaborators_remove.go, cmd/autocomplete/db_tunnel.go, cmd/autocomplete/env_unset.go, cmd/autocomplete/region_migrations.go, cmd/error.go, config/auth.go, crypto/sshkeys/agent.go, db/backup_create.go, db/tunnel.go, io/spinner.go, logs/logs.go, notifiers/details.go, region_migrations/refresher.go, session/login.go, stacks/set.go, term/term_unix.go, utils/helper.go
Updated the CodeShip configuration according to our new procedure
=> style(golangci-lint): autofixes

CHANGELOG.md, dists/install.sh
The install script does not need to check if an update is avbailable when calling `scalingo --version`.
Fix #536
=>  fix(install): disable CLI update checker 

CHANGELOG.md, apps/destroy.go, cmd/destroy.go
Fix https://github.com/Scalingo/cli/issues/678
=> add an option (--force) allowing to destroy an app without interactive confirmation

CHANGELOG.md, cmd/error.go
```
 scalingo integrations-delete github
!     400 Bad Request → integration is still used by application repo links:
- Region 'osc-fr1': Application 'biniou-2'
- Region 'osc-fr1': Application 'biniou'
```
Fix #743
=> fix(error): interpret raw newline

CHANGELOG.md, dists/install.sh
=> fix(install.sh): better error message if fails to get the version

.github/workflows/publish.yml, CHANGELOG.md, dists/make-release.sh
Execution example:
```
emichon@biniou  ~/Documents/Scalingo/golang/src/github.com/Scalingo/cli   fix/739/gox ✚  ./dists/make-release.sh -j 3 -v $VERSION
Remove previously compiled binaries
Compiling the binaries for all architectures
Number of parallel builds: 3
-->     linux/amd64: github.com/Scalingo/cli/scalingo
-->     windows/386: github.com/Scalingo/cli/scalingo
-->     linux/arm64: github.com/Scalingo/cli/scalingo
-->     freebsd/386: github.com/Scalingo/cli/scalingo
-->   freebsd/amd64: github.com/Scalingo/cli/scalingo
-->    darwin/amd64: github.com/Scalingo/cli/scalingo
-->   openbsd/amd64: github.com/Scalingo/cli/scalingo
-->     openbsd/386: github.com/Scalingo/cli/scalingo
-->    darwin/arm64: github.com/Scalingo/cli/scalingo
-->   windows/amd64: …
```
=> feat(make-release): use gox

.github/workflows/dependabot.yml
If it updates a minor or patch version.
Inspired from https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request
=> feat(workflows): auto-merge Dependabot PRs

CHANGELOG.md, utils/git.go
=> fix(appdetect) Do not crash if the git config has a remote without any URL

.github/workflows/dependabot.yml
as per the official doc: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions\#enable-auto-merge-on-a-pull-request
The Dependabot PRs from past month batch hadn't been auto-merged due to permission problem.
=> fix(workflows): add contents write permissions

.github/workflows/publish.yml
The `release` job is executed after `tests`, if it's successful.
Based on this doc: https://docs.github.com/en/actions/using-workflows/about-workflows#creating-dependent-jobs
=> feat(workflows/publish): split in two jobs

CHANGELOG.md, cmd/db_tunnel.go, cmd/influxdb.go, cmd/mongo.go, cmd/mysql.go, cmd/pgsql.go, cmd/redis.go, db/env.go, db/influxdb_console.go, db/mongo_console.go, db/mysql_console.go, db/pgsql_console.go, db/redis_console.go
~@johnsudaar I would like a review of what I did for MongoDB console, and if it's LGTM I just need to propagate the same change to all database types~
Fix #387
=> feat(db): environment variable name is customizable

CHANGELOG.md, README.md, config/version.go
> [Changelog] CLI - Release of version 1.24.0 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> Bump version 1.24.0

dists/install.sh
Fix [SRE-688]
[SRE-688]: https://scalingo.atlassian.net/browse/SRE-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(installer) Mac OSX artefacts do not use zip anymore

cmd/notifiers.go
=> fix(notifiers): Unable to add a notifier when no collaborator are specified

cmd/integration_link.go
Fix the problem that did not display the error in the specific case where the auto deploy flag is activated but no branch to deploy is specified.
In addition, all errors are now displayed instead of being skipped.
```sh
$ scalingo -a escudierq-test integration-link-create --auto-deploy https://github.com/QuentinEscudierScalingo/sample-go-martini
!     An error occurred:
fail to create the repo link: fail to create the SCM repo link: * auto_deploy_enabled → branch can't be blank
```
Fixes #765
=> fix(integration-link): no error when --auto-deploy and no branch specified

.github/workflows/publish.yml, .goreleaser-windows.yaml, .goreleaser.yaml
With this PR, the `publish` action has two different jobs for the GoReleaser execution:
- `releases-windows`: execute GoReleaser on a Windows server so that we don't use Go cross compile feature. This is to prevent issues such as the one described in #734.
- `releases`: execute GoReleaser on a Ubuntu server for OpenBSD, Linux and macOS using Go cross compile feature. 
All these features are added as assets of a single GitHub release. You can see an example of execution on my fork: https://github.com/EtienneM/cli/releases/tag/1.25.2-beta8. One of the cons from my perspective is that we have two different files for the checksums. 
Related to #734 and #735
=> feat(publish): compile Windows release on Windows

cmd/log_drains.go
This PR introduce new examples about AppSignal compatibility and the new token parameter for syslog (tcp+tls)
FIX #813
=> docs(log-drains): appsignal and syslog tcp+tls examples

cmd/log_drains.go, logdrains/add.go, logdrains/list.go, logdrains/remove.go
Will be merged the 15th of November 2022.
I also renamed the package `log_drains` to `logdrains` as it's a convention in Go that packages name don't contain `_`.
Fix #819
n/a:
=> fix(logdrains): delete Logentries mentions

CHANGELOG.md, README.md, cmd/influxdb.go, cmd/mongo.go
It actually already exists for `pgsql-console`.
Fix #828
=> feat(db-console): add `influx-console` and `mongodb-console` aliases

CHANGELOG.md, README.md, apps/sendsignal.go, cmd/commands.go, cmd/sendsignal.go, go.mod, go.sum, vendor/github.com/Scalingo/go-scalingo/v6/CHANGELOG.md, vendor/github.com/Scalingo/go-scalingo/v6/README.md, vendor/github.com/Scalingo/go-scalingo/v6/apps.go, vendor/github.com/Scalingo/go-scalingo/v6/container.go, vendor/github.com/Scalingo/go-scalingo/v6/events_structs.go, vendor/github.com/Scalingo/go-scalingo/v6/version.go, vendor/github.com/golang-jwt/jwt/v4/README.md, vendor/github.com/golang-jwt/jwt/v4/claims.go, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v4/token.go, vendor/modules.txt
```
» ./scalingo help send-signal                                                                                                                                                     
NAME:
scalingo send-signal - Send SIGUSR1 or SIGUSR2 to your application containers
USAGE:
scalingo send-signal [command options] [arguments...]
CATEGORY:
App Management
DESCRIPTION:
Send SIGUSR1 or SIGUSR2 to your application containers
Example
'scalingo --app my-app send-signal --signal SIGUSR1 web-1'
'scalingo --app my-app send-signal --signal SIGUSR2 web-1 web-2'
OPTIONS:
--app value, -a value     Name of the current app
--signal value, -s value  signal to send to the container
--region value            Name of the region to use
--help, -h                show help (default: false)
```
Fix #832
=> feat(send-signal): send-signal command added

apps/sendsignal.go
Sorry for this pr, I didn't notice that io.Error print a new line.
Fix #844
=> fix(send-signal): remove trailing whitespace when container not found

go.mod, go.sum, vendor/github.com/ScaleFT/sshkeys/marshal.go, vendor/modules.txt
=> chore(deps): bump github.com/ScaleFT/sshkeys from v0.0.0-20200327173127-6142f742bca5 to v1.2.0

.github/workflows/publish.yml, CHANGELOG.md
=> fix(cli-build) Compile the CLI statically to prevent GLIBC incompatibility

cmd/commands.go
This PR fixes #865 
It fixes the regression introduced with #835 
This is the line that disabled the `--help` flag and the floating `help` sub-command. So I've only disabled the `help` sub-command.
I wondered why the issues #834 
and
#831 
I investigated and the root problem was : when calling the `cli.ShowCommandHelp`, our command's help is not found.
urfave cli is introducing a subcommand in every command. The subcommand `help`. So we can do for example `scalingo create help` and the help should be displayed.
When the number of args is invalid, we call the command `cli.ShowCommandHelp` with our commands' name. But here is the catch.
Here is the problem. In the function code : 
If our command has subcommands : it will restrict its search to the subcommands. And our command has a …
=> fix(commands): brought back --help command

CHANGELOG.md, cmd/backups.go
Bug introduced in #868.
Fix #891
=> fix(backups): `backup` flag is not required

CHANGELOG.md, cmd/integration_link.go, integrationlink/params.go, integrationlink/show.go
contributes to https://github.com/Scalingo/project-items/issues/68
depends on https://github.com/Scalingo/go-scalingo/pull/300
need to do a `go mod vendor` after https://github.com/Scalingo/go-scalingo/pull/300 before merging this
=> feat: add an option to allow review app creation from forks

apps/operations.go, apps/run.go, cmd/run.go, go.mod, go.sum, vendor/github.com/Scalingo/go-scalingo/v6/CHANGELOG.md, vendor/github.com/Scalingo/go-scalingo/v6/Dockerfile, vendor/github.com/Scalingo/go-scalingo/v6/README.md, vendor/github.com/Scalingo/go-scalingo/v6/backups.go, vendor/github.com/Scalingo/go-scalingo/v6/deployments.go, vendor/github.com/Scalingo/go-scalingo/v6/operations.go, vendor/github.com/Scalingo/go-scalingo/v6/run.go, vendor/github.com/Scalingo/go-scalingo/v6/version.go, vendor/github.com/Scalingo/go-utils/errors/v2/CHANGELOG.md, vendor/github.com/Scalingo/go-utils/errors/v2/LICENSE, vendor/github.com/Scalingo/go-utils/errors/v2/README.md, vendor/github.com/Scalingo/go-utils/errors/v2/cause.go, vendor/github.com/Scalingo/go-utils/errors/v2/errctx.go, vendor/github.com/Scalingo/go-utils/errors/v2/errgo.go, vendor/github.com/Scalingo/go-utils/errors/v2/errors.go, vendor/github.com/Scalingo/go-utils/errors/v2/validation_errors.go, vendor/modules.txt
fix #901 
(proposed: `----> Starting container [one-off-####]  + Spinner`)
require https://github.com/Scalingo/go-scalingo/pull/317
=> feat(one-off): allow attached one-off to be run asynchronously

apps/operations.go, apps/restart.go, apps/run.go, apps/scale.go
=> refacto(wait-operation) Fix extra space in output and make the code a bit clearer

db/influxdb_console.go, db/mongo_console.go, db/mysql_console.go, db/pgsql_console.go, db/redis_console.go
Related to #901
```
└> ./scalingo --app test-app pgsql-console
You do not have consent for this app, Override ? (y/n) y
-----> Starting container one-off-7985  Done in 7.121 seconds
-----> Connecting to container [one-off-7985]...
-----> Process 'pgsql-console test-app-1234' is starting...
---> Download and extract the database CLI
---> Database CLI installed:
psql (PostgreSQL) 14.6
psql (14.6, server 12.11 (Debian 12.11-1.pgdg90+1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
test-app-1234=>
```
=> Use async one-off for database console commands

cmd/error.go, cmd/integration_link.go, integrationlink/show.go
No need to add changelog entries
Fixes https://github.com/Scalingo/cli/issues/921
I also changed the way the integration settings are displayed, using go templates. I think this is much clearer than doing it programmatically, if you have some returns let me know
(sorry etienne, github does not allow me to remove you from the reviewers)
=> feat(review-apps) wording changes

CHANGELOG.md, dists/install.sh
Hello,
This PR adds support for the ARM64 architecture in the magic install script, since you have already been kind enough to build binaries for these processors, both for Linux and for macOS.
This will allow to quickly install the CLI on a Raspberry Pi or a Mac M1/M2! 🥳 
Thanks a lot!
Works on Raspberry Pi with Raspberry Pi OS 64 bit:
```
joseph@raspberrypi-8go:~ $ uname -a
Linux raspberrypi-8go 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux
joseph@raspberrypi-8go:~ $ curl -O https://raw.githubusercontent.com/josephpage/cli/arm64-in-install-script/dists/install.sh && bash install.sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  4203  100  4203    0     0   5347      0 --:--:-- …
```
=> feat(install.sh): add arm64 architecture

cmd/addons.go, cmd/alerts.go, cmd/autoscalers.go, cmd/backups.go, cmd/collaborators.go, cmd/databases.go, cmd/deployments.go, cmd/destroy.go, cmd/domains.go, cmd/integration_link.go, cmd/log_drains.go, cmd/notifiers.go, cmd/one_off_stop.go, cmd/region_migrations.go, cmd/rename.go, cmd/restart.go, cmd/routing_settings.go, cmd/scale.go, cmd/sendsignal.go, cmd/stacks.go
=> fix(consent) Add consent for more commands

cmd/addons.go
⬆️ Do I need to update the changelog for a change this small?
Also I'm wondering if this command shouldn't use the `--addon` params like other command?
=> fix: correct example in documentation

CHANGELOG.md, cmd/integration_link.go, go.mod, go.sum, integrationlink/manual_deploy.go, vendor/github.com/Scalingo/go-scalingo/v6/CHANGELOG.md, vendor/github.com/Scalingo/go-scalingo/v6/README.md, vendor/github.com/Scalingo/go-scalingo/v6/client.go, vendor/github.com/Scalingo/go-scalingo/v6/events_boilerplate.go, vendor/github.com/Scalingo/go-scalingo/v6/events_specialize.go, vendor/github.com/Scalingo/go-scalingo/v6/events_structs.go, vendor/github.com/Scalingo/go-scalingo/v6/scm_repo_link.go, vendor/github.com/Scalingo/go-scalingo/v6/users.go, vendor/github.com/Scalingo/go-scalingo/v6/version.go, vendor/modules.txt
Depends on https://github.com/Scalingo/go-scalingo/pull/332
=> feat(integration-link): add --follow arg to manual-deploy command

CHANGELOG.md, cmd/env.go, env/edit.go, env/edit_test.go, go.mod, go.sum, vendor/github.com/joho/godotenv/.gitignore, vendor/github.com/joho/godotenv/LICENCE, vendor/github.com/joho/godotenv/README.md, vendor/github.com/joho/godotenv/godotenv.go, vendor/github.com/joho/godotenv/parser.go, vendor/modules.txt
This add a new flag `--file` to the `env-set` subcommand to read from an env file or read from stdin.
This should fix #782
=> Set env variables from a file

CHANGELOG.md, dists/install.sh
=> feat(install.sh): change default target directory for Apple Silicon

CHANGELOG.md, cmd/addons.go, cmd/backups.go, cmd/databases.go, cmd/flags.go, cmd/log_drains.go, cmd/logs.go, cmd/logs_archives.go, db/logs.go, utils/addon_uuid.go
=> feat: addon param can be an addon type name

CHANGELOG.md, dists/install.sh
If valid, output is:
```
-----> Downloading Scalingo client...  DONE
-----> Verifying the checksum...  VALID
[...]
```
If invalid, output is:
```
-----> Downloading Scalingo client...  DONE
-----> Verifying the checksum...  INVALID
!     Checksums don't match ('3fdec56b8647953744fe4c9094dd7b0a0952b1cb9416bc7e315cde00b8db557a' != '3fdec56b8647953744fe4c9094dd7b0a0952b1cb9416bc7e315cde00b8db557a')
!     You may want to retry to install the Scalingo CLI. If the problem persists, please contact our support team.
```
I'm not sure we want to keep displaying the checksums in the error message, what do you think?
Fix #422
=> feat(install.sh): verify the archive checksum

dists/install.sh
~~- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md~~
Fixes #1001
=> fix(install): for MacOS compatibility, remove usage of long parameter for cut and tr

apps/info.go
While investigating #976, I found this error message incomplete
Didn't do the following as it does not seem really interesting to highlight in the changelog:
=> fix(apps): add stack ID in error message

dists/install.sh
Fixes https://github.com/Scalingo/cli/issues/1012
Tested on Benjamin's Mac
=> fix(install): remove wget and sha256sum dependencies

CHANGELOG.md, go.mod, go.sum, vendor/github.com/Scalingo/go-scalingo/v6/CHANGELOG.md, vendor/github.com/Scalingo/go-scalingo/v6/README.md, vendor/github.com/Scalingo/go-scalingo/v6/events_structs.go, vendor/github.com/Scalingo/go-scalingo/v6/version.go, vendor/modules.txt
```
❯ go run scalingo/main.go --app biniou timeline
* Wed Dec 20 2023 15:18:23 - Link Scm           - app has been linked to repository 'EtienneM/sample-go-gin' <etiennem (etienne@scalingo.com)>
```
Fix #1022
=> fix(events): `link_scm` data types

CHANGELOG.md, cmd/databases.go
=> feat(cmd): add aliases for database user management

.github/workflows/publish.yml
The CI currently fails on master. For instance: https://github.com/Scalingo/cli/actions/runs/7900369881/job/21561746176
This is because of the error:
```
level=warning msg="[runner] Can't process result by diff processor: can't prepare diff by revgrep: could not read git repo: error executing git diff \"HEAD~1\" \"\": exit status 128"
```
This PR is a fix for the code introduced in #758
n/a:
=> build(publish): fech depth to 2 for linter on master branch

CHANGELOG.md, cmd/commands.go, cmd/databases.go, db/users/create.go, db/users/delete.go, db/users/list.go, db/users/update.go, db/users/utils.go, go.mod, go.sum, vendor/github.com/Scalingo/go-scalingo/v6/CHANGELOG.md, vendor/github.com/Scalingo/go-scalingo/v6/README.md, vendor/github.com/Scalingo/go-scalingo/v6/databases.go, vendor/github.com/Scalingo/go-scalingo/v6/http/client.go, vendor/github.com/Scalingo/go-scalingo/v6/version.go, vendor/modules.txt
Max retry reached
```bash
➜ scalingo --app my-app --addon mysql database-users-update-password my_user
Password (Will be generated if left empty): 
Password Confirmation: 
!     Password confirmation doesn't match. Remaining retries: 2
Password (Will be generated if left empty): 
Password Confirmation: 
!     Password confirmation doesn't match. Remaining retries: 1
Password (Will be generated if left empty): 
Password Confirmation: 
!     Password confirmation doesn't match. Too many retries
```
User does not exists
```bash
➜ scalingo --app my-app --addon mysql database-users-update-password user_does_not_exists
!     An error occurred:
User "user_does_not_exists" does not exist
```
It works after a retry
```bash
➜ scalingo --app my-app --addon mysql database-users-update-password …
```
=> feat(cmd): add database user password update

db/users/delete.go, db/users/update.go, db/users/utils.go
~~- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md~~
=> fix(users): user feedback messages improvements

.github/workflows/publish.yml
=> fix(actions): test conditional needs

CHANGELOG.md, addons/info.go, db/utils.go, go.mod, go.sum
```sh
➜  scalingo --app $APPNAME addons-info ad-42d531f2-c985-47b9-b7f1-6771c8ced235
+----------------+-----------------------+
| Addon Provider | Scalingo Docker Image |
| Plan           | base-plan             |
| Status         | running               |
+----------------+-----------------------+
➜  scalingo --app $APPNAME addons-info ad-5656af19-eda5-4f00-afec-3c1cd726f960
+----------------+--------------------+
| Addon Provider | Scalingo VPN IPSec |
| Plan           | vpn-ipsec-standard |
| Status         | running            |
+----------------+--------------------+
➜  scalingo --app $APPNAME addons-info postgresql
+------------------------+--------------------------------+
| Addon Provider         | PostgreSQL                     |
| Plan                   | postgresql-starter-512 …
```
=> fix(cmd): addons-info working for non-db addons

CHANGELOG.md, cmd/databases.go, db/users/update_password.go, go.mod, go.sum, vendor/github.com/Scalingo/go-scalingo/v7/CHANGELOG.md, vendor/github.com/Scalingo/go-scalingo/v7/README.md, vendor/github.com/Scalingo/go-scalingo/v7/apps.go, vendor/github.com/Scalingo/go-scalingo/v7/databases.go, vendor/github.com/Scalingo/go-scalingo/v7/version.go, vendor/modules.txt
Database user password update uses new API endpoint for generating password.
This is dependent on the merging / release of the equivalent branch in go-scalingo library.
[Story 642](https://www.notion.so/scalingooriginal/New-API-endpoint-to-handle-password-reset-662bd5bb9ec045308e5348f499055e65)
=> [STORY-642] new api endpoint to handle password reset

CHANGELOG.md, db/users/create.go, db/users/update_password.go, db/users/utils.go, db/users/utils_test.go
DB user passwords length must be between 24 to 64.
STORY-648
=> [STORY-648] feat: raise DB user passwords minimum length to 24

.sclng/metadata.toml
I noticed that we didn't initialized this repository with Asgard
=> it does not seem relevant to add a changelog entry for such change
=> build(asgard): initialize

.github/workflows/publish.yml, CHANGELOG.md, apps/operations.go, git/setup.go, go.mod, utils/errors.go
=> deps: update go from 1.23.4 to 1.24.2

CHANGELOG.md, cmd/domains.go, domains/list.go
Fix #1047
Output on a sample app:
```
go run ./scalingo --app my-app domains
┌──────────────────────────────────────────────┬───────────────┬──────────────────────────────────────────────────┬─────────────────────────────┬────────────────────────────────────────────────────────┐
│                    DOMAIN                    │   TLS / SSL   │                   TLS SUBJECT                    │ LET ' S ENCRYPT CERTIFICATE │                     MANUAL ACTION                      │
├──────────────────────────────────────────────┼───────────────┼──────────────────────────────────────────────────┼─────────────────────────────┼────────────────────────────────────────────────────────┤
│ redacted-domain.fr                           │ Let's Encrypt │ /CN=redacted-domain.fr …
```
=> feat(domains): add 'Manual Action' column if needed

CHANGELOG.md, cmd/privatenetworks.go
`table` is the default format in all the CLI. I think it should still be the same.
=> fix(privatenetworks): default format should be `table`
