Scalingo/cli

db/tunnel.go

Manage DES-EDE3-CBC RSA encrypted keys

---

apps/destroy.go

This doesn't build, a compilation error "No new variables on left side of :=" is raised

Fix "no new variable defined" error

---

CHANGELOG

Changelog update v1.1.2

---

apps/destroy.go

Newline character trimmed from user input

Fix #177 Destroy command fixed

---

CHANGELOG
Godeps/Godeps.json
addons/provision.go
apps/create.go
apps/scale.go
cmd/create.go
cmd/error.go
utils/helper.go
vendor/github.com/Scalingo/go-scalingo/errors.go
vendor/github.com/Scalingo/go-scalingo/profile.go
vendor/github.com/Scalingo/go-scalingo/users.go

CLI handle early end of free trial

---

cmd/authenticate.go

Adds support of an api token env var

---

update/check.go

Adds timeout on update check

---

db/mongo_console.go

Signed-off-by: Jonathan Hurter <john@scalingo.com>

Add replicaset support

---

CHANGELOG
apps/run.go

Better error message for one-off inactivity timeout

---

apps/run.go
apps/run/run_unix.go
apps/run/run_windows.go

Send tty size on first container byte

---

dists/install.sh

The installation script gains these options:
```
-h, --help             displays help and exits
-i, --install-dir DIR  scalingo client installation directory, creating it if
necessary (defaults to /usr/local/bin)
-y, --yes              accepts overwriting previously installed scalingo client
```
I used to run the following snippet to install scalingo client in my home bin directory and avoid using `sudo`:
```
[...]
curl -sSL https://cli-dl.scalingo.io/install | sed "s#/usr/local/bin#$bin_path#" > "$scalingo_install_file" && echo Y | bash "$scalingo_install_file"
```
With this PR, I will be able to run
```
curl -O https://cli-dl.scalingo.io/install && bash install -y -i "$HOME/bin"
```

Add options for unattended install in custom directory

---

cmd/addons_providers_plans_list.go
vendor/github.com/Scalingo/go-scalingo/addons_providers.go

be less strict about addon name

---

CHANGELOG
apps/logs.go

[logs] filter accepts one-off and postdeploy container

---

Gopkg.lock
Gopkg.toml
cmd/commands.go
cmd/deployments.go
deployments/cache.go
vendor/github.com/Scalingo/go-scalingo/addons.go
vendor/github.com/Scalingo/go-scalingo/apps.go
vendor/github.com/Scalingo/go-scalingo/auth_api_token.go
vendor/github.com/Scalingo/go-scalingo/autoscalers.go
vendor/github.com/Scalingo/go-scalingo/client.go
vendor/github.com/Scalingo/go-scalingo/deployments.go
vendor/github.com/Scalingo/go-scalingo/domains.go
vendor/github.com/Scalingo/go-scalingo/github_link.go
vendor/github.com/Scalingo/go-scalingo/keys.go
vendor/github.com/Scalingo/go-scalingo/metrics.go
vendor/github.com/Scalingo/go-scalingo/subresources.go
vendor/github.com/Scalingo/go-scalingo/tokens.go

User is able to reset deployment cache

---

deployments/follow.go

Since multiple deployment can be run on parallel and the new event is not always fetched, ensure logs are streamed after 'scalingo deploy .jar/war

---

CHANGELOG
Gopkg.lock
Gopkg.toml
cmd/notifiers.go
collaborators/list.go
notifiers/create.go
notifiers/details.go
notifiers/update.go
vendor/github.com/Scalingo/go-scalingo/collaborators.go
vendor/github.com/Scalingo/go-scalingo/events_boilerplate.go
vendor/github.com/Scalingo/go-scalingo/events_types.go
vendor/github.com/Scalingo/go-scalingo/notifier_types.go
vendor/github.com/Scalingo/go-scalingo/notifiers.go
vendor/github.com/Scalingo/go-scalingo/users.go

```
scalingo -a notifiers-add --platform email --collaborator soulou --email notify@example.com --email monitoring@example.com
```
Fixes #364

Add the ability to add email notifiers

---

apps/logs.go

Consider CTRL^C the normal way to stop a logs -f, not an error

---

CHANGELOG
cmd/commands.go
cmd/env.go
cmd/help.go
cmd/restart.go
env/edit.go
env/edit_test.go

```
$ scalingo -a biniou env-set TOTO=titi
TOTO has been set to 'titi'.
Please restart your containers:
scalingo --app biniou restart
```
Fix #373

Advise to restart the containers after setting environment

---

CHANGELOG
cmd/error.go

```
$ scalingo -a biniou env-unset TOTO
!     You are currently logged in as customer1.
!     Are you sure customer1 is a collaborator of this app?
```
Fix #352

Better error message if 401 Unauthorized

---

CHANGELOG
Gopkg.lock
Gopkg.toml
apps/routing_settings.go
cmd/apps.go
cmd/commands.go
cmd/domains.go
cmd/routing_settings.go
domains/add.go
domains/canonical.go
domains/list.go
vendor/github.com/Scalingo/go-scalingo/addons.go
vendor/github.com/Scalingo/go-scalingo/alerts.go
vendor/github.com/Scalingo/go-scalingo/apps.go
vendor/github.com/Scalingo/go-scalingo/autoscalers.go
vendor/github.com/Scalingo/go-scalingo/collaborators.go
vendor/github.com/Scalingo/go-scalingo/container.go
vendor/github.com/Scalingo/go-scalingo/domains.go
vendor/github.com/Scalingo/go-scalingo/events_types.go
vendor/github.com/Scalingo/go-scalingo/notification_platforms.go
vendor/github.com/Scalingo/go-scalingo/notifier_types.go
vendor/github.com/Scalingo/go-scalingo/operations.go
vendor/github.com/Scalingo/go-scalingo/subresources.go
vendor/github.com/olekukonko/tablewriter/util.go

Fix #344
```text
$ scalingo -a biniou force-https [--enable]
-----> Force HTTPS has been enabled on biniou
```
```text
$ scalingo -a biniou force-https --disable
-----> Force HTTPS has been disabled on biniou
```
```text
$ scalingo -a biniou sticky-session [--enable]
-----> Sticky session has been enabled on biniou
```
```text
$ scalingo -a biniou sticky-session --disable
-----> Sticky session has been disabled on biniou
```
```text
$ scalingo -a biniou domains
+-----------------+-----+
|     DOMAIN      | SSL |
+-----------------+-----+
| biniou.fr       |   - |
| example.com (*) |   - |
+-----------------+-----+
(*) canonical domain
```
```text
$ scalingo -a biniou set-canonical-domain biniou.fr
-----> Canonical domain set to biniou.fr
```
```text
$ scalingo -a biniou …
```

Add routing settings

---

CHANGELOG
Gopkg.lock
vendor/github.com/Scalingo/go-scalingo/events_types.go

Update go-scalingo to fix missing spaces

---

crypto/sshkeys/read.go
net/ssh/client.go

New version of ssh package requrie HostKeyCallback, default value to ignore

---

db/tunnel.go

Output human messages on stderr and ADDR:PORT on stdout for easier
machine parsing

Output only machine-parseable info on stdout

---

Gopkg.lock
Gopkg.toml
vendor/github.com/Scalingo/go-scalingo/http/client.go

Related to https://github.com/Scalingo/go-scalingo/issues/79

Fix default value for the DB API URL

---

addons/destroy.go
addons/upgrade.go

Accept new format of ID for addon operations upgrade/destroy

---

addon_providers/plans.go

... and add the price. Don't we want to display it?
Fix #408

Remove Description from addon plans

---

CHANGELOG.md
session/login.go

Fix login with SSH

---

cmd/commands.go
cmd/self.go
user/self.go

self/whoami commands are now checking the user with the API

---

CHANGELOG.md
Gopkg.lock
vendor/github.com/Scalingo/go-scalingo/http/api_request.go

Update go-scalingo to display the request ID

---

cmd/autocomplete/collaborators_add.go
cmd/autocomplete/stacks.go
cmd/stacks.go

Fix #429
I'm unsure about how the autocomplete works if you can tell me if it's OK

Various improvements to stacks-set

---

CHANGELOG.md
notifiers/list.go

Do not look for selected events if notifier sends all events

---

Gopkg.lock
Gopkg.toml
apps/routing_settings.go
autoscalers/remove.go
autoscalers/update.go
cmd/commands.go
cmd/error.go
config/auth.go
session/login.go
utils/helper.go
vendor/github.com/Scalingo/go-scalingo/apps.go
vendor/github.com/Scalingo/go-scalingo/http/api_request.go
vendor/github.com/Scalingo/go-scalingo/http/client.go
vendor/github.com/Scalingo/go-scalingo/http/errors.go
vendor/github.com/Scalingo/go-scalingo/tokens.go
vendor/github.com/Scalingo/go-utils/errors/cause.go
vendor/github.com/Scalingo/go-utils/errors/errctx.go
vendor/github.com/Scalingo/go-utils/errors/errgo.go
vendor/github.com/Scalingo/go-utils/errors/validation_errors.go
vendor/github.com/bmizerany/assert/assert.go
vendor/github.com/kr/pretty/License
vendor/github.com/kr/pretty/diff.go
vendor/github.com/kr/pretty/formatter.go
vendor/github.com/kr/pretty/pretty.go
vendor/github.com/kr/pretty/zero.go
vendor/github.com/kr/text/License
vendor/github.com/kr/text/doc.go
vendor/github.com/kr/text/indent.go
vendor/github.com/kr/text/wrap.go

~Waiting for https://github.com/Scalingo/go-scalingo/pull/114 to be merged~ merged!
Fix #447

Only fill regions cache for regional commands

---

CHANGELOG.md
Gopkg.lock
cmd/databases.go
vendor/github.com/Scalingo/go-scalingo/databases.go

```
╰─$ scalingo --app test-etienne --addon ad-d4903c5a-7b38-4fca-950a-54a34ae84ca4 backups-config --schedule-at "5"
!     An error occured:
Your database is backed up multiple times a day at 5:00, 14:00 CEST. Please ask the support to update the frequency of these backups.
```
Related to Scalingo/appsdeck-database#1181

PeriodicBackupsScheduledAt can contain multiple values

---

CHANGELOG.md
cmd/error.go

Do not disconnect user on 401

---

Gopkg.lock
Gopkg.toml
config/auth.go
config/config.go
config/region.go
session/login.go
vendor/github.com/Scalingo/go-scalingo/apps.go
vendor/github.com/Scalingo/go-scalingo/client.go
vendor/github.com/Scalingo/go-scalingo/events_boilerplate.go
vendor/github.com/Scalingo/go-scalingo/events_structs.go
vendor/github.com/Scalingo/go-scalingo/events_user.go
vendor/github.com/Scalingo/go-scalingo/http/client.go
vendor/github.com/Scalingo/go-scalingo/regions.go
vendor/github.com/Scalingo/go-scalingo/scm_repo_link.go

```
$ scalingo --app test-etienne timeline
* Wed Aug 21 2019 13:13:20 - Link Scm      - app has been linked to repository 'EtienneM/sample-go-martini' <etiennem (etienne@scalingo.com)>
* Wed Aug 21 2019 13:11:58 - Unlink Scm    - app has been unlinked from repository 'EtienneM/sample-go-martini' <etiennem (etienne@scalingo.com)>
```
Fix #466

Add support for new SCM events

---

README.md
apps/run.go
config/auth.go
config/auth_test.go
config/config_test.go
keys/add.go

Setup Codeship

---

CHANGELOG.md
deployments/list.go

```text
╰─$ go build -o ./scalingo/scalingo ./scalingo && ./scalingo/scalingo -a rss-bridge deployments
+--------------------------------------+---------------------+----------+----------+------------------------------------------+-------------+
|                  ID                  |        DATE         | DURATION |   USER   |                 GIT REF                  |   STATUS    |
+--------------------------------------+---------------------+----------+----------+------------------------------------------+-------------+
| 8399e52a-0f15-4177-b646-02ec0904758a | 2019/07/29 09:07:18 | 2m8s     | etiennem | 2dde3ebc67b009a22dddfdabd4d7f77b4dee66d4 | success     |
| 52707a76-e066-460f-ab56-ad0f9803c642 | 2019/07/29 09:05:04 | 43s      | etiennem | 2dde3ebc67b009a22dddfdabd4d7f77b4dee66d4 | …
```

Add duration to deployments list

---

CHANGELOG.md
cmd/commands.go
cmd/keys.go
config/config.go
keys/add.go
keys/list.go
keys/remove.go
regions/regions.go
scmintegrations/create.go
scmintegrations/delete.go
scmintegrations/import_keys.go
scmintegrations/list.go
user/self.go

Global commands should use an client to Scalingo auth

---

CHANGELOG.md

Missing changelog.
Updating go-scalingo in #492 solved this issue.
Fix #490

Better handling of 404 auth query

---

CHANGELOG.md
integrationlink/create.go

Fix creation of an integration link

---

integrationlink/create.go

Fix incorrect code, leading to a incorrect error message on integration-link-create

---

CHANGELOG.md
integrationlink/create.go

Fix error management in integration-link-create

---

region_migrations/status.go

Fixes https://github.com/Scalingo/one-stop-shop/issues/64

Display command to aboart the migration just after migration-create

---

region_migrations/status.go

[Migration] Instruction to change git URL

---

Gopkg.lock
cmd/region_migrations.go
region_migrations/follow.go
region_migrations/refresher.go
region_migrations/utils.go
vendor/github.com/Scalingo/go-scalingo/region_migrations.go
vendor/github.com/Scalingo/go-scalingo/version.go

[Migration] Explain what's the current state is doing

---

Gopkg.lock
Gopkg.toml
region_migrations/refresher.go
vendor/github.com/Scalingo/go-utils/errors/validation_errors.go
vendor/github.com/Scalingo/go-utils/retry/retry.go

Use new retrier to manage refresh tries

---

CHANGELOG.md
Gopkg.lock
deployments/deploy.go
deployments/follow.go
vendor/github.com/Scalingo/go-scalingo/deployments.go
vendor/github.com/Scalingo/go-scalingo/version.go

Send an non zero exit code when the deploy command fails

---

README.md
config/config.go
dists/make-release.sh

I tested the make-release script and it works, it injects the Rollbar token :)

Make make-release.sh work in the current branch

---

cmd/log_drains.go

on log drains addition: add a warning for addons and new option: --with-databases

---

CHANGELOG.md
Gopkg.lock
deployments/deploy.go
vendor/github.com/Scalingo/go-scalingo/deployments.go
vendor/github.com/Scalingo/go-scalingo/version.go

Close #585 
Merge then make a release of the `CLI`

Handle new `queued` deployment status

---

CHANGELOG.md
cmd/log_drains.go

[logs-drain-remove] Do not panic if no args are provided

---

CHANGELOG.md

[changelog] Fix typo

---

README.md
dists/make-release.sh

Add more responsibilities to the make-release.sh script

---

CHANGELOG.md
config/region.go
go.mod
go.sum
session/login.go
vendor/github.com/Scalingo/go-scalingo/CHANGELOG.md
vendor/github.com/Scalingo/go-scalingo/README.md
vendor/github.com/Scalingo/go-scalingo/http/api_request.go
vendor/github.com/Scalingo/go-scalingo/http/client.go
vendor/github.com/Scalingo/go-scalingo/http/httpmock/client_mock.go
vendor/github.com/Scalingo/go-scalingo/mocks_sig.json
vendor/github.com/Scalingo/go-scalingo/version.go
vendor/modules.txt

Make an unauthenticated request to fetch the region cache on login

---

CHANGELOG.md
addons/list.go

Add AddonStatus on scalingo addons command

---

CHANGELOG.md
cmd/commands.go
cmd/deployments.go
cmd/self.go

feat(deployment-cache-delete): add as alias to deployment-delete-cache

---

CHANGELOG.md
cmd/backups.go
db/backup_download.go

```
-----> Selected the most recent backup
88 B / 88 B [=============================================...=] 100.00% 0s
===> 20210331000000_biniou-7148.tar.gz
```
Fix #533

feat(backups-download): download most recent backup if none is provided

---

CHANGELOG.md
cmd/integration_link.go
scmintegrations/utils.go

feat(integration-link-create): automatically prfix the integration URL with https if none is provided

---

cmd/run.go

I didn't add a CHANGELOG entry, it does not seem worth it...
Fix #566

docs(run): specify max file size limit

---

cmd/alerts.go

I didn't add a CHANGELOG entry, it does not seem worth it...
Fix #601

fix(alerts-update): typo in help message

---

cmd/error.go
config/region.go

I didn't add a CHANGELOG entry, it does not seem worth it...
Fix #532

fix(error): clearer error message in case of unknown region

---

CHANGELOG.md
io/status.go

fix(error): output on stderr

---

deployments/deploy.go
log_drains/add.go

I think these TODOs were never an actual issue. Let's remove them and open issue later if it's needed

fix: remove TODO

---

.github/dependabot.yml

feat(dependabot): EtienneM assigned to review as owner of the project

---

CHANGELOG.md
review_apps/show.go

Add the URL of the review-app in the table writer.
Fix #612

Fix(review-app-url) add app url in the tablewriter

---

CHANGELOG.md
apps/logs.go
apps/run.go
cmd/autocomplete/current_app.go
config/auth.go
crypto/sshkeys/read.go
db/backup_download.go
deployments/deploy.go
domains/ssl.go
go.mod
keys/add.go
update/check.go

Update(ioutil) Remove deprecated lib 'ioutil'

---

dists/install.sh

fix(install): Scalingo starts with an upper case

---

CHANGELOG.md
README.md
cmd/commands.go
cmd/deployments.go
cmd/pgsql.go
cmd/self.go

feat(pgsql-console): add aliases

---

CHANGELOG.md
cmd/run.go

fix(run): display an error message for detached one-off with uploaded files

---

CHANGELOG.md
apps/run.go

fix(run): --region flag in help message

---

cmd/update.go

See https://scalingo.slack.com/archives/CRC7L0XM2/p1643814997682299

Improve `update` description

---

.github/dependabot.yml
.github/workflows/publish.yml
README.md

feat(actions): inital setup to execute the tests

---

CHANGELOG.md
cmd/autoscalers.go

fix(autoscalers): min containers cannot be 1

---

CHANGELOG.md
apps/stats.go

fix(stats): display memory as IEC size

---

CHANGELOG.md
cmd/logs.go
db/logs.go

feat(logs): possibility to get the addon logs by using its type (e.g. Redis)

---

README.md

~~- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md~~

docs(readme): add additional information related to the release

---

.gitignore
.goreleaser.yaml
CHANGELOG.md

fix(goreleaser) Generate zip archives for windows

---

.goreleaser.yaml
CHANGELOG.md

fix(goreleaser): use github native changelog generation

---

CHANGELOG.md
cmd/autocomplete/current_app.go
cmd/backups.go
cmd/commands.go
cmd/config.go
cmd/create.go
cmd/databases.go
cmd/flags.go
cmd/git.go
cmd/log_drains.go
detect/app.go
detect/region.go

Fix https://github.com/Scalingo/cli/issues/780

fix(cli): Fix detection --app, --region, --remote and --addon from command line arguments

---

CHANGELOG.md
cmd/stacks.go
go.mod
go.sum
stacks/list.go
vendor/github.com/Scalingo/go-scalingo/v5/CHANGELOG.md
vendor/github.com/Scalingo/go-scalingo/v5/README.md
vendor/github.com/Scalingo/go-scalingo/v5/events.go
vendor/github.com/Scalingo/go-scalingo/v5/events_account.go
vendor/github.com/Scalingo/go-scalingo/v5/events_addon.go
vendor/github.com/Scalingo/go-scalingo/v5/events_boilerplate.go
vendor/github.com/Scalingo/go-scalingo/v5/events_specialize.go
vendor/github.com/Scalingo/go-scalingo/v5/events_structs.go
vendor/github.com/Scalingo/go-scalingo/v5/stacks.go
vendor/modules.txt

Refs. https://github.com/scalingo/api/issues/1831

feat(stacks): Add possibility to show deprecated stacks

---

notifiers/create.go
notifiers/list.go

Fix the crash when trying to list a no-event notifier
Fix the typo Notifier have been created -> Notifier has been createdFixes #777
Fixes #777

fix(notifier): no-event notifier

---

cmd/deployments.go
deployments/list.go

#778 Deployments pagination

---

CHANGELOG.md
cmd/domains.go
cmd/integration_link.go
cmd/scm_integrations.go

fix(arguments): Update the changelog to hilight the breaking change

---

apps/run/run_windows.go

https://github.com/Scalingo/cli/actions/runs/3067097267/jobs/4953026082

Fix goreleaser failure for windows build

---

cmd/backups.go
cmd/db_tunnel.go
cmd/env.go
cmd/git.go
cmd/influxdb.go
cmd/logs.go
cmd/logs_archives.go
cmd/mongo.go
cmd/mysql.go
cmd/pgsql.go
cmd/redis.go
cmd/run.go
cmd/timeline.go
detect/app.go
utils/consent.go

This is the bare minimum, waiting for the full API to be released

feature(data_access_consent) Add support for data_access_consent

---

deployments/deploy.go
deployments/deploy_war.go

While investigating #825 I fixed these linter offenses
n/a

fix(deployments): missing err check

---

CHANGELOG.md
db/logs.go

feat(logs): allow DB type aliases

---

CHANGELOG.md
cmd/addons.go
cmd/commands.go
cmd/flags.go

You may want to review commit by commit as this PR also contains a bunch of refactoring.
I think the scenario described in the related issue actually never worked.. 😅  
Fix #834
This PR also fixes #831
I would like to release a new version after this PR.

fix(commands): display help usage message if needed

---

CHANGELOG.md
apps/sendsignal.go
cmd/sendsignal.go

feat(send-signal): Allow to send signals to multiple containers via its type

---

cmd/stacks.go

No need of a changelog entry for this IMHO

fix: use a current stacks in help

---

.github/workflows/dependabot.yml

Related to https://github.com/Scalingo/project-items/issues/10
=> not applicable

refactor(workflows): make use of ghaction-dependabot-automerge

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/Scalingo/go-scalingo/v6/CHANGELOG.md
vendor/github.com/Scalingo/go-scalingo/v6/http/errors.go
vendor/modules.txt

bump: go-scalingo v6.2.0

---

CHANGELOG.md

Bump 1.27.2

---

.github/workflows/publish.yml
CHANGELOG.md

build(publish): replace `rm-dist` with `clean`

---

CHANGELOG.md
cmd/autocomplete/scripts/scalingo_complete.zsh

fix(completion): fix zsh shebang ref

---

cmd/integration_link.go

Fixing some reviews from https://github.com/Scalingo/project-items/issues/91

fix: wording on review apps from fork deploy warning

---

CHANGELOG.md
cmd/flags.go

~- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md~
Related to https://github.com/Scalingo/cli/pull/983

fix(flags): addon flag is not needed for logs commands

---

dists/install.sh

I was getting this error when installing Scalingo CLI

fix errors -> error

---

dists/install.sh

~~- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md~~

fix(install): if shasum not available fall back on sha256sum

---

addonproviders/list.go
addonproviders/plans.go
alerts/add.go
alerts/list.go
alerts/remove.go
alerts/update.go
crontasks/list.go
deployments/cache.go
deployments/deploy.go
deployments/deploy_war.go
deployments/follow.go
deployments/list.go
deployments/logs.go
integrationlink/create.go
integrationlink/delete.go
integrationlink/manual_deploy.go
integrationlink/manual_review_app.go
integrationlink/pull_request.go
integrationlink/update.go
session/login.go

Just the most straightforwards occurrences

refactor(deployments): replace errgo with ErrCtx

---

CHANGELOG.md
scalingo/main.go

fix(autocomplete): do not show update message on autocomplete

---

.github/workflows/publish.yml

Successfully tested on my fork: https://github.com/EtienneM/cli/actions/runs/8296674349/job/22706174229
n/a:

fix(workflows): write permissions

---

cmd/databases.go

style(backups) clearer error message

---

cmd/addons.go

Update example command for addon creation by postgres and not mongo ([slack](https://scalingo.slack.com/archives/CRC7L0XM2/p1753114173064849))
Question: do I really need a changelog entry for this? :arrow_down:

[STORY-2297] Update example command for addon creation

---

.github/CODEOWNERS

build(CODEOWNERS): assign IST for Dependabot's PRs
